### ISSUE TITLE
Broken links to Ecto Models Guide

### ISSUE THREAD

**Issue by earthrid** [hexpm/hexpm#562] opened 2017-08-28 17:18 UTC
The following pages link to the "Ecto Models Guide" but all give a "Page not found" error.

https://hexdocs.pm/phoenix/seeding_data.html
"as described in the Ecto Models Guide" 

https://hexdocs.pm/phoenix/testing_models.html
"In the Ecto Models Guide we generated an HTML resource for users."
+
"If this is not the case, please see the section on adding Ecto and Postgrex of the Ecto Models Guide and join us when that’s done."

https://hexdocs.pm/phoenix/file_uploads.html
"In the Ecto Models Guide, we generated an HTML resource for users."

https://hexdocs.pm/phoenix/controllers.html
"We cover how to use Ecto in a Phoenix project in the Ecto Models Guide."

https://hexdocs.pm/phoenix/testing.html
"and the Ecto Models Guide dives into the details on how it all works."

**Comment by wojtekmach** [comment] 2017-08-28 17:51
Thanks for reporting! The issue is in phoenix guides, they link to a page that doesn't exist anymore:

See: https://github.com/phoenixframework/phoenix_guides/blame/master/docs/testing/testing_models.md#L3

It should probably link to [`ecto.html`](https://hexdocs.pm/phoenix/ecto.html). Could you open up an issue or ideally a PR on https://github.com/phoenixframework/phoenix_guides? Closing since it's not actionable in this repo.

**Closed by wojtekmach** 2017-08-28 17:51 UTC

**Comment by earthrid** [comment] 2017-08-28 18:26
Thanks @wojtekmach! I wasn't sure... :)
