### ISSUE TITLE
fix navbar layout on mobile

### ISSUE THREAD

**Issue by faraazahmad** [hexpm/hexpm#596] opened 2017-12-09 08:31 UTC
[
![screenshot_20171209-135828](https://user-images.githubusercontent.com/19265077/33794022-1c429832-dcbb-11e7-8c3a-beb25e0e43d2.png)
](url)

Here we can see the navbar is not properly aligned, it would be great if this got fixed

**Comment by ericmj** [comment] 2017-12-09 11:26
I can't reproduce this on my devices or stepping through the device list in Chrome. What device and browser are you using?

Any help fixing this would be appreciated.

**Comment by faraazahmad** [comment] 2017-12-09 13:21
Firefox and Firefox NIghtly on Android 7.0. It's probably also happening on Firefox Beta

**Comment by ericmj** [comment] 2017-12-09 13:48
Thanks.

I cant reproduce with Firefox in responsive mode on desktop and I don't have an Android device that can reproduce either. Any help with this issue would be appreciated.

**Comment by faraazahmad** [comment] 2017-12-09 15:13
I think Firefox is using a slightly different rendering engine on their android browsers. I assume you have iOS, can you check with Firefox on that?

**Comment by ericmj** [comment] 2017-12-10 01:47
I can't reproduce on iOS Firefox. I think all iOS browsers uses the Mobile Safari engine.

**Comment by juhalehtonen** [comment] 2017-12-13 21:58
Can confirm that this issue occurs on the latest Firefox for Android, which contain updates to the engine released around the time when Quantum landed on Firefox for desktops. Earlier versions of Firefox for Android are not affected. 

You're also completely correct with your thought regarding Firefox for iOS using Apple's Safari/WebKit engine :)

Opened https://github.com/hexpm/hexpm/pull/598 which fixes this.

**Closed** 2017-12-17 21:04 UTC
Labels: Kind:Bug
